apiVersion: batch/v1
kind: Job
metadata:
  name: log-ingestion-job
spec:
  parallelism: 5  # Specify the number of desired pods
  completions: 5  # Adjust as needed
  template:
    metadata:
      labels:
        app: log-ingestion
    spec:
      containers:
      - name: log-ingestion-container
        image: ignite23.azurecr.io/my-ingest-image:1.0   ###update to your image name 
      restartPolicy: Never
